import { WeeklyReport } from './types'

export const BALTIC_REPORT: WeeklyReport = {
  id: 'baltic-613-9c-w1',
  // Week 8 — this week's reporting window (June 21 – June 27, 2026).
  weekNumber: 8,
  reportDate: '2026-06-23',
  weekStartDate: '2026-06-21',
  weekEndDate: '2026-06-27',

  property: {
    address: '613 Baltic Street',
    unit: 'Unit 9C',
    neighborhood: 'Park Slope',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11217',
    price: 3_249_000,
    beds: 3,
    baths: 3.5,
    sqft: 1789,
    listingDate: '2026-05-07',
    mainImageUrl: '/613-baltic-listing.jpg',
    galleryImages: [],
    description:
      'A standout corner three-bedroom, three-and-one-half-bath home defined by great light, open southwest exposures, and exceptional outdoor space. Set high above the neighborhood with nearly 1,800 square feet of interior space and two private terraces, the home feels expansive in a way that\'s increasingly rare in New York. Floor-to-ceiling windows flood every room with natural light while framing panoramic skyline views. Included with the residence are secure underground parking and private storage.',
    agent: {
      name: 'Maggie L. Marshall',
      title: 'Licensed Associate Real Estate Broker',
      team: 'MM&Co.',
      brokerage: 'Compass',
      phone: '917-838-4774',
      email: 'mlm@compass.com',
      photoUrl: '/613-baltic-agent.jpg',
      logoUrl: '/mmco-logo.png',
    },
    coAgents: [
      {
        name: 'Cyrus Blake',
        title: 'Licensed Real Estate Salesperson',
        team: 'MM&Co.',
        brokerage: 'Compass',
        phone: '207-412-9907',
        email: '',
        photoUrl: '/cyrus-blake-headshot.webp',
        logoUrl: '/mmco-logo.png',
      },
    ],
  },

  // Week 8 (Jun 21 – Jun 27, 2026).
  // Compass Insights pulled for Jun 19 – Jun 25: 268 total views (147 Compass /
  // 121 StreetEasy), 114 unique visitors, 8s avg time spent. Compass was the
  // top traffic source at 56% of visitors; 86% of Compass views from the public.
  currentMetrics: {
    totalViews: 268,
    websiteTraffic: 0,
    zillowViews: 0,
    streetEasyViews: 121,
    compassViews: 147,
    saves: 0,
    inquiries: 0,
    showingRequests: 0,
    // Sunday Jun 21 open house — one couple came through.
    openHouseAttendees: 2,
    brokerInquiries: 0,
    buyerLeads: 0,
    socialReach: 0,
    videoViews: 0,
  },

  // Previous = prior week (Jun 14–20) for week-over-week comparison.
  previousMetrics: {
    totalViews: 351,
    websiteTraffic: 0,
    zillowViews: 0,
    streetEasyViews: 92,
    compassViews: 259,
    saves: 0,
    inquiries: 0,
    showingRequests: 0,
    openHouseAttendees: 4,
    brokerInquiries: 0,
    buyerLeads: 0,
    socialReach: 0,
    videoViews: 0,
  },

  metricsHistory: [
    {
      weekLabel: 'Week 1',
      weekNumber: 1,
      metrics: {
        totalViews: 998,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 312,
        compassViews: 686,
        saves: 0,
        inquiries: 0,
        showingRequests: 1,
        openHouseAttendees: 2,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 2',
      weekNumber: 2,
      metrics: {
        totalViews: 545,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 141,
        compassViews: 404,
        saves: 17,
        inquiries: 3,
        showingRequests: 1,
        openHouseAttendees: 4,
        brokerInquiries: 0,
        buyerLeads: 4,
        socialReach: 555,
        videoViews: 555,
      },
    },
    {
      weekLabel: 'Week 3',
      weekNumber: 3,
      metrics: {
        totalViews: 293,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 117,
        compassViews: 176,
        saves: 0,
        inquiries: 0,
        showingRequests: 0,
        openHouseAttendees: 0,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 4',
      weekNumber: 4,
      metrics: {
        totalViews: 285,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 134,
        compassViews: 151,
        saves: 0,
        inquiries: 0,
        showingRequests: 1,
        openHouseAttendees: 11,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 5',
      weekNumber: 5,
      metrics: {
        totalViews: 380,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 79,
        compassViews: 301,
        saves: 0,
        inquiries: 0,
        showingRequests: 0,
        openHouseAttendees: 0,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      // Week 6 was the missed week; using the Compass insights pull for
      // Jun 11 – Jun 17 as the closest snapshot.
      weekLabel: 'Week 6',
      weekNumber: 6,
      metrics: {
        totalViews: 351,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 92,
        compassViews: 259,
        saves: 0,
        inquiries: 0,
        showingRequests: 0,
        openHouseAttendees: 0,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
  ],

  includedSections: {
    propertyOverview: false,
    weeklySnapshot:   true,
    openHouses:       true,
    marketing:        true,
    socialMedia:      false,
    digitalAds:       true,
    feedback:         false,
    marketActivity:   false,
    strategy:         true,
  },

  openHouses: [
    {
      id: 'oh-baltic-000',
      date: '2026-05-10',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 2,
      brokers: 0,
      buyers: 2,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: '',
    },
    {
      id: 'oh-baltic-001',
      date: '2026-05-17',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 4,
      brokers: 3,
      buyers: 1,
      seriousInterestLevel: 4,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'One buyer requesting a second private showing — scheduled for Friday May 22.',
    },
    {
      id: 'oh-baltic-002',
      date: '2026-05-24',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 0,
      brokers: 0,
      buyers: 0,
      seriousInterestLevel: 1,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'Memorial Day weekend — no attendees.',
    },
    {
      id: 'oh-baltic-003',
      date: '2026-05-28',
      startTime: '18:30',
      endTime: '20:30',
      totalAttendees: 11,
      brokers: 11,
      buyers: 0,
      seriousInterestLevel: 4,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'Broker Open House — 11 NYC brokers attended. Strong showing from the broker network.',
    },
    // Weeks 6–7 open houses — one couple at each of three events.
    {
      id: 'oh-baltic-w6-sun',
      kind: 'public',
      date: '2026-06-14',
      startTime: '13:00',
      endTime: '14:30',
      totalAttendees: 2,
      brokers: 0,
      buyers: 2,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'One couple attended — first showing at the new $3.25M price.',
    },
    {
      id: 'oh-baltic-w6-wed',
      kind: 'public',
      date: '2026-06-17',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 2,
      brokers: 0,
      buyers: 2,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'Midweek open house — one couple attended.',
    },
    {
      id: 'oh-baltic-w7-sun',
      kind: 'public',
      date: '2026-06-21',
      startTime: '13:00',
      endTime: '14:30',
      totalAttendees: 2,
      brokers: 0,
      buyers: 2,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'One couple attended — steady weekend interest at the new price.',
    },
  ],

  marketing: [
    {
      id: 'mkt-baltic-001',
      type: 'instagram_reel',
      name: '@maggie_leigh_marshall — Open House Reel',
      date: '2026-05-16',
      impressions: 555,
      engagement: 36,
      clicks: 0,
      reach: 555,
      link: 'https://www.instagram.com/reel/DYYJSRdsVFO/',
      notes:
        'Reel on @maggie_leigh_marshall (Verified) announcing Sunday May 17 open house. Highlights 1,800 SF, two private terraces, floor-to-ceiling windows, panoramic skyline views. Collaboration with @soldbycy. Hashtags: #parkslope #balticparkslope #MM&Co.',
    },
    {
      id: 'mkt-baltic-stories',
      type: 'instagram_post',
      name: '@soldbycy — Instagram Story Series',
      date: '2026-05-14',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: '4-part Instagram story series posted by @soldbycy highlighting 613 Baltic Street Unit 9C. Property walkthrough and lifestyle content.',
    },
    {
      id: 'mkt-baltic-broker-blast',
      type: 'broker_outreach',
      name: 'Broker Blast — NYC Network',
      date: '2026-05-15',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes: 'Targeted email blast sent to 8,000+ NYC brokers announcing 613 Baltic Street, Unit 9C.',
    },
    {
      id: 'mkt-baltic-broker-blast-w3',
      type: 'broker_outreach',
      name: 'Broker Blast — NYC Network (weekly)',
      date: '2026-05-23',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes: 'Weekly broker blast — 8,000+ NYC brokers reminded of the listing and upcoming open houses.',
    },
    {
      id: 'mkt-baltic-w3-mm-post',
      type: 'instagram_post',
      name: '@maggie_leigh_marshall — Open House Post',
      date: '2026-05-23',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: 'Open house announcement post on @maggie_leigh_marshall (Verified) promoting the Sunday May 24 and Thursday May 28 open houses.',
    },
    {
      id: 'mkt-baltic-w3-soldbycy-post',
      type: 'instagram_post',
      name: '@soldbycy — Open House Post',
      date: '2026-05-27',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: 'Open house announcement post on @soldbycy promoting the May 28 Wine & Cheese Sunset Open House.',
    },
    {
      id: 'mkt-baltic-w3-stories',
      type: 'instagram_post',
      name: '@soldbycy + @maggie_leigh_marshall — Instagram Stories',
      date: '2026-05-26',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: '3 Instagram stories across @soldbycy and @maggie_leigh_marshall featuring 613 Baltic Street, Unit 9C.',
    },
    {
      id: 'mkt-baltic-002',
      type: 'instagram_post',
      name: '@compassny — 613 Baltic Street Launch Post',
      date: '2026-05-20',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      link: 'https://www.instagram.com/p/DYm-xYpkUN_/',
      notes:
        'Posted on @compassny (Verified) and reshared across team accounts. Caption highlights corner 3BR/3.5BA, southwest exposures, outdoor space, parking + storage. Tagged @maggie_leigh_marshall.',
    },
    {
      id: 'mkt-baltic-w5-price-drop',
      type: 'instagram_post',
      name: '@maggie_leigh_marshall — Price Drop Announcement',
      date: '2026-06-09',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes:
        'Instagram post highlighting the recent price adjustment to $3,249,000 (down from $3,500,000). Drives new buyer attention and re-engages prior viewers.',
    },
    {
      id: 'mkt-baltic-w5-broker-blast',
      type: 'broker_outreach',
      name: 'Price Drop Broker Blast — NYC Network',
      date: '2026-06-09',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes:
        'Targeted email blast to the full NYC broker community announcing the price adjustment to $3,249,000. Reactivates brokers with $3M–$3.5M buyers who may not have looked at the higher price.',
    },
    {
      id: 'mkt-baltic-w6-broker-blast',
      type: 'broker_outreach',
      name: 'Broker Blast — NYC Network (Week 6)',
      date: '2026-06-17',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes:
        'Weekly broker blast to the full NYC agent network — reinforcing the $3,249,000 price.',
    },
    {
      id: 'mkt-baltic-w7-broker-blast',
      type: 'broker_outreach',
      name: 'Broker Blast — NYC Network (Week 7)',
      date: '2026-06-19',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes:
        'Weekly broker blast to the full NYC agent network — promoting the Sunday June 21 open house and continued availability at $3,249,000.',
    },
  ],

  socialMedia: [
    {
      platform: 'instagram',
      reelViews: 555,
      likes: 23,
      comments: 0,
      shares: 13,
      saves: 0,
      engagementRate: 0,
      followerGrowth: 0,
      bestContentDescription: '@maggie_leigh_marshall open house reel — 613 Baltic St, Unit 9C. 555 views.',
      bestContentViews: 555,
    },
  ],

  feedback: {
    items: [],
    commonObjections: '',
    pricingFeedback: '',
    layoutFeedback: '',
    competingProperties: '',
    brokerSentiment: '',
    recommendedAdjustments: '',
  },

  digitalAds: {
    campaignName: 'Location-Based Targeting',
    targetingFocus: 'Boerum Hill · Park Slope · Cobble Hill · Carroll Gardens · Brooklyn Heights · Fort Greene',
    // Latest Compass Digital Ads pull — Jun 21 – Jun 27, 2026 (Databox).
    reportingPeriod: 'Jun 21 – Jun 27, 2026',
    totalImpressions: 15425,
    totalClicks: 111,
    topChannel: { name: 'nytimes.com', ctr: 0.72 },
    byChannel: [
      { channel: 'Google',    clicks: 88, ctr: 1.82 },
      { channel: 'Facebook',  clicks: 19, ctr: 1.73 },
      { channel: 'Instagram', clicks: 14, ctr: 2.48 },
    ],
    // Top 12 publishers from the Jun 21 – Jun 27 Databox snapshot.
    topPublishers: [
      { publisher: 'nytimes.com',     views: 3643 },
      { publisher: 'nypost.com',      views: 1968 },
      { publisher: 'theatlantic.com', views: 853  },
      { publisher: 'huffpost.com',    views: 769  },
      { publisher: 'gothamist.com',   views: 562  },
      { publisher: 'yahoo.com',       views: 528  },
      { publisher: 'npr.org',         views: 485  },
      { publisher: 'therealdeal.com', views: 348  },
      { publisher: 'foxnews.com',     views: 348  },
      { publisher: 'collive.com',     views: 337  },
      { publisher: 'thedailybeast.com', views: 315 },
      { publisher: 'cnn.com',         views: 310  },
    ],
    audienceHouseholdIncome: [
      { bracket: 'Top 10%', share: 90.3 },
      { bracket: '41–50%',  share: 5.0  },
      { bracket: '21–30%',  share: 2.1  },
    ],
    // Carrying forward Jun 11 – Jun 17 social split until the next pull.
    socialTrafficPeriod: 'June 11 – June 17, 2026',
    socialTrafficShare: [
      { channel: 'Facebook',  share: 61.0 },
      { channel: 'Instagram', share: 39.0 },
    ],
  },

  marketActivity: {
    newListings: [],
    priceReductions: [],
    underContract: [],
    recentSales: [],
    neighborhoodTrends:
      'StreetEasy data: 613 Baltic is significantly outperforming comparable Park Slope listings on views — 463 total views in just 14 days against a median of 36.5 for similar homes. Median days to contract for comparable homes is 132 days. Strong early momentum positions the listing well.',
  },

  strategy: {
    keyRecommendations: '',
    marketingPlanNextWeek: '— Continue $3.25M price-adjustment push across all social and display creatives\n— Refresh Instagram content — Facebook still leads social traffic, push fresh Reels + Stories to rebalance Instagram\n— Location-based display campaign continues — NYT (3.6K views), NYPost, The Atlantic, HuffPost, Gothamist, Yahoo, NPR, The Real Deal all driving steady ad views\n— Weekly broker blast to NYC network',
    pricingStrategy: '',
    upcomingCampaigns: '',
    brokerEvents: '',
    openHousesPlanned: '— Public open house: Sunday June 28, 1:00–2:30 PM',
  },
}
