import { WeeklyReport } from './types'

export const BALTIC_REPORT: WeeklyReport = {
  id: 'baltic-613-9c-w1',
  weekNumber: 4,
  reportDate: '2026-06-04',
  weekStartDate: '2026-05-28',
  weekEndDate: '2026-06-03',

  property: {
    address: '613 Baltic Street',
    unit: 'Unit 9C',
    neighborhood: 'Park Slope',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11217',
    price: 3_500_000,
    beds: 3,
    baths: 3.5,
    sqft: 1789,
    listingDate: '2026-05-07',
    mainImageUrl: '/613-baltic-listing.jpg',
    galleryImages: [],
    description:
      'A standout corner three-bedroom, three-and-one-half-bath home defined by great light, open southwest exposures, and exceptional outdoor space. Set high above the neighborhood with nearly 1,800 square feet of interior space and two private terraces, the home feels expansive in a way that\'s increasingly rare in New York. Floor-to-ceiling windows flood every room with natural light while framing panoramic skyline views. Included with the residence are secure underground parking and private storage.',
    agent: {
      name: 'Maggie L. Marshall',
      title: 'Licensed Associate Real Estate Broker',
      team: 'MM&Co.',
      brokerage: 'Compass',
      phone: '917-838-4774',
      email: 'mlm@compass.com',
      photoUrl: '/613-baltic-agent.jpg',
      logoUrl: '/mmco-logo.png',
    },
    coAgents: [
      {
        name: 'Cyrus Blake',
        title: 'Licensed Real Estate Salesperson',
        team: 'MM&Co.',
        brokerage: 'Compass',
        phone: '207-412-9907',
        email: '',
        photoUrl: '/cyrus-blake-headshot.webp',
        logoUrl: '/mmco-logo.png',
      },
    ],
  },

  // Week 4 (May 28 – June 3): broker open house Thursday with 9 attendees.
  // Compass Insights (May 28 – June 3): 285 total views, 117 unique visitors,
  // 151 Compass / 134 StreetEasy. 86% of Compass views from public visitors.
  // Top traffic source: Social (43%); top social channel: Instagram (85%).
  currentMetrics: {
    totalViews: 285,
    websiteTraffic: 0,
    zillowViews: 0,
    streetEasyViews: 134,
    compassViews: 151,
    saves: 0,
    inquiries: 0,
    showingRequests: 0,
    openHouseAttendees: 9,
    brokerInquiries: 0,
    buyerLeads: 0,
    socialReach: 0,
    videoViews: 0,
  },

  // Previous = Week 3's actuals so trends still compute
  previousMetrics: {
    totalViews: 293,
    websiteTraffic: 0,
    zillowViews: 0,
    streetEasyViews: 117,
    compassViews: 176,
    saves: 0,
    inquiries: 0,
    showingRequests: 0,
    openHouseAttendees: 0,
    brokerInquiries: 0,
    buyerLeads: 0,
    socialReach: 0,
    videoViews: 0,
  },

  metricsHistory: [
    {
      weekLabel: 'Week 1',
      weekNumber: 1,
      metrics: {
        totalViews: 998,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 312,
        compassViews: 686,
        saves: 0,
        inquiries: 0,
        showingRequests: 1,
        openHouseAttendees: 2,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 2',
      weekNumber: 2,
      metrics: {
        totalViews: 545,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 141,
        compassViews: 404,
        saves: 17,
        inquiries: 3,
        showingRequests: 1,
        openHouseAttendees: 4,
        brokerInquiries: 0,
        buyerLeads: 4,
        socialReach: 555,
        videoViews: 555,
      },
    },
    {
      weekLabel: 'Week 3',
      weekNumber: 3,
      metrics: {
        totalViews: 293,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 117,
        compassViews: 176,
        saves: 0,
        inquiries: 0,
        showingRequests: 0,
        openHouseAttendees: 0,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 4',
      weekNumber: 4,
      metrics: {
        totalViews: 285,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 134,
        compassViews: 151,
        saves: 0,
        inquiries: 0,
        showingRequests: 0,
        openHouseAttendees: 9,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
  ],

  includedSections: {
    propertyOverview: false,
    weeklySnapshot:   true,
    openHouses:       true,
    marketing:        true,
    socialMedia:      true,
    feedback:         false,
    marketActivity:   false,
    strategy:         true,
  },

  openHouses: [
    {
      id: 'oh-baltic-000',
      date: '2026-05-10',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 2,
      brokers: 0,
      buyers: 2,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: '',
    },
    {
      id: 'oh-baltic-001',
      date: '2026-05-17',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 4,
      brokers: 3,
      buyers: 1,
      seriousInterestLevel: 4,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'One buyer requesting a second private showing — scheduled for Friday May 22.',
    },
    {
      id: 'oh-baltic-002',
      date: '2026-05-24',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 0,
      brokers: 0,
      buyers: 0,
      seriousInterestLevel: 1,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'Memorial Day weekend — no attendees.',
    },
    {
      id: 'oh-baltic-003',
      date: '2026-05-28',
      startTime: '18:30',
      endTime: '20:30',
      totalAttendees: 9,
      brokers: 9,
      buyers: 0,
      seriousInterestLevel: 4,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'Broker Open House — 9 NYC brokers attended. Strong showing from the broker network.',
    },
  ],

  marketing: [
    {
      id: 'mkt-baltic-001',
      type: 'instagram_reel',
      name: '@maggie_leigh_marshall — Open House Reel',
      date: '2026-05-16',
      impressions: 555,
      engagement: 36,
      clicks: 0,
      reach: 555,
      link: 'https://www.instagram.com/reel/DYYJSRdsVFO/',
      notes:
        'Reel on @maggie_leigh_marshall (Verified) announcing Sunday May 17 open house. Highlights 1,800 SF, two private terraces, floor-to-ceiling windows, panoramic skyline views. Collaboration with @soldbycy. Hashtags: #parkslope #balticparkslope #MM&Co.',
    },
    {
      id: 'mkt-baltic-stories',
      type: 'instagram_post',
      name: '@soldbycy — Instagram Story Series',
      date: '2026-05-14',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: '4-part Instagram story series posted by @soldbycy highlighting 613 Baltic Street Unit 9C. Property walkthrough and lifestyle content.',
    },
    {
      id: 'mkt-baltic-broker-blast',
      type: 'broker_outreach',
      name: 'Broker Blast — NYC Network',
      date: '2026-05-15',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes: 'Targeted email blast sent to 8,000+ NYC brokers announcing 613 Baltic Street, Unit 9C.',
    },
    {
      id: 'mkt-baltic-broker-blast-w3',
      type: 'broker_outreach',
      name: 'Broker Blast — NYC Network (weekly)',
      date: '2026-05-23',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes: 'Weekly broker blast — 8,000+ NYC brokers reminded of the listing and upcoming open houses.',
    },
    {
      id: 'mkt-baltic-w3-mm-post',
      type: 'instagram_post',
      name: '@maggie_leigh_marshall — Open House Post',
      date: '2026-05-23',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: 'Open house announcement post on @maggie_leigh_marshall (Verified) promoting the Sunday May 24 and Thursday May 28 open houses.',
    },
    {
      id: 'mkt-baltic-w3-soldbycy-post',
      type: 'instagram_post',
      name: '@soldbycy — Open House Post',
      date: '2026-05-27',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: 'Open house announcement post on @soldbycy promoting the May 28 Wine & Cheese Sunset Open House.',
    },
    {
      id: 'mkt-baltic-w3-stories',
      type: 'instagram_post',
      name: '@soldbycy + @maggie_leigh_marshall — Instagram Stories',
      date: '2026-05-26',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: '3 Instagram stories across @soldbycy and @maggie_leigh_marshall featuring 613 Baltic Street, Unit 9C.',
    },
    {
      id: 'mkt-baltic-002',
      type: 'instagram_post',
      name: '@compassny — 613 Baltic Street Launch Post',
      date: '2026-05-20',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      link: 'https://www.instagram.com/p/DYm-xYpkUN_/',
      notes:
        'Posted on @compassny (Verified) and reshared across team accounts. Caption highlights corner 3BR/3.5BA, southwest exposures, outdoor space, parking + storage. Tagged @maggie_leigh_marshall.',
    },
  ],

  socialMedia: [
    {
      platform: 'instagram',
      reelViews: 555,
      likes: 23,
      comments: 0,
      shares: 13,
      saves: 0,
      engagementRate: 0,
      followerGrowth: 0,
      bestContentDescription: '@maggie_leigh_marshall open house reel — 613 Baltic St, Unit 9C. 555 views.',
      bestContentViews: 555,
    },
  ],

  feedback: {
    items: [],
    commonObjections: '',
    pricingFeedback: '',
    layoutFeedback: '',
    competingProperties: '',
    brokerSentiment: '',
    recommendedAdjustments: '',
  },

  digitalAds: {
    campaignName: 'Location-Based Targeting',
    targetingFocus: 'Boerum Hill · Park Slope · Cobble Hill · Carroll Gardens · Brooklyn Heights · Fort Greene',
    reportingPeriod: 'May 29 – June 28, 2026',
    totalImpressions: 21943,
    totalClicks: 122,
    cpc: 0.94,
    topChannel: { name: 'nytimes.com', ctr: 0.56 },
    byChannel: [], // Display campaign — no per-social-channel clicks; see topPublishers below
    topPublishers: [
      { publisher: 'nytimes.com',                       views: 3277 },
      { publisher: 'theatlantic.com',                   views: 2452 },
      { publisher: 'mlb.com',                           views: 1720 },
      { publisher: 'nypost.com',                        views: 1658 },
      { publisher: 'foxnews.com',                       views: 1043 },
      { publisher: 'huffpost.com',                      views: 1008 },
      { publisher: 'theguardian.com',                   views: 735 },
      { publisher: 'Newsday (Mobile App)',              views: 621 },
      { publisher: 'npr.org',                           views: 612 },
      { publisher: 'yahoo.com',                         views: 501 },
      { publisher: 'thedailybeast.com',                 views: 414 },
      { publisher: 'cnn.com',                           views: 365 },
    ],
    audienceHouseholdIncome: [
      { bracket: 'Top 10%', share: 92.9 },
      { bracket: '41–50%',  share: 3.6  },
      { bracket: '21–30%',  share: 1.7  },
    ],
    socialTrafficPeriod: 'May 28 – June 3, 2026',
    socialTrafficShare: [
      { channel: 'Instagram', share: 85.0 },
      { channel: 'Facebook',  share: 15.0 },
    ],
  },

  marketActivity: {
    newListings: [],
    priceReductions: [],
    underContract: [],
    recentSales: [],
    neighborhoodTrends:
      'StreetEasy data: 613 Baltic is significantly outperforming comparable Park Slope listings on views — 463 total views in just 14 days against a median of 36.5 for similar homes. Median days to contract for comparable homes is 132 days. Strong early momentum positions the listing well.',
  },

  strategy: {
    keyRecommendations: '',
    marketingPlanNextWeek: '— Personal follow-up with all 9 brokers from the Thursday May 28 broker open house\n— New Instagram reel highlighting the broker-event turnout and terrace views\n— Continued posts across @maggie_leigh_marshall and @soldbycy\n— Weekly broker blast to NYC network\n— Continue location-based display campaign (NYT, Atlantic, NY Post, etc.) through June 28',
    pricingStrategy: '',
    upcomingCampaigns: '',
    brokerEvents: '',
    openHousesPlanned: '— Public open house: Sunday June 7, 12:00–1:30 PM',
  },
}
