import { WeeklyReport } from './types'

export const BALTIC_REPORT: WeeklyReport = {
  id: 'baltic-613-9c-w1',
  weekNumber: 5,
  reportDate: '2026-06-11',
  weekStartDate: '2026-06-04',
  weekEndDate: '2026-06-10',

  property: {
    address: '613 Baltic Street',
    unit: 'Unit 9C',
    neighborhood: 'Park Slope',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11217',
    price: 3_249_000,
    beds: 3,
    baths: 3.5,
    sqft: 1789,
    listingDate: '2026-05-07',
    mainImageUrl: '/613-baltic-listing.jpg',
    galleryImages: [],
    description:
      'A standout corner three-bedroom, three-and-one-half-bath home defined by great light, open southwest exposures, and exceptional outdoor space. Set high above the neighborhood with nearly 1,800 square feet of interior space and two private terraces, the home feels expansive in a way that\'s increasingly rare in New York. Floor-to-ceiling windows flood every room with natural light while framing panoramic skyline views. Included with the residence are secure underground parking and private storage.',
    agent: {
      name: 'Maggie L. Marshall',
      title: 'Licensed Associate Real Estate Broker',
      team: 'MM&Co.',
      brokerage: 'Compass',
      phone: '917-838-4774',
      email: 'mlm@compass.com',
      photoUrl: '/613-baltic-agent.jpg',
      logoUrl: '/mmco-logo.png',
    },
    coAgents: [
      {
        name: 'Cyrus Blake',
        title: 'Licensed Real Estate Salesperson',
        team: 'MM&Co.',
        brokerage: 'Compass',
        phone: '207-412-9907',
        email: '',
        photoUrl: '/cyrus-blake-headshot.webp',
        logoUrl: '/mmco-logo.png',
      },
    ],
  },

  // Week 5 (June 4 – June 10): Price adjustment announced — listed at $3,249,000.
  // Compass Insights (June 4 – June 10): 380 total views,
  // 301 Compass / 79 StreetEasy.
  // Top social channel: Facebook (77.1% of social traffic).
  currentMetrics: {
    totalViews: 380,
    websiteTraffic: 0,
    zillowViews: 0,
    streetEasyViews: 79,
    compassViews: 301,
    saves: 0,
    inquiries: 0,
    showingRequests: 0,
    openHouseAttendees: 0,
    brokerInquiries: 0,
    buyerLeads: 0,
    socialReach: 0,
    videoViews: 0,
  },

  // Previous = Week 4's actuals so trends still compute
  previousMetrics: {
    totalViews: 285,
    websiteTraffic: 0,
    zillowViews: 0,
    streetEasyViews: 134,
    compassViews: 151,
    saves: 0,
    inquiries: 0,
    showingRequests: 1,
    openHouseAttendees: 11,
    brokerInquiries: 0,
    buyerLeads: 0,
    socialReach: 0,
    videoViews: 0,
  },

  metricsHistory: [
    {
      weekLabel: 'Week 1',
      weekNumber: 1,
      metrics: {
        totalViews: 998,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 312,
        compassViews: 686,
        saves: 0,
        inquiries: 0,
        showingRequests: 1,
        openHouseAttendees: 2,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 2',
      weekNumber: 2,
      metrics: {
        totalViews: 545,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 141,
        compassViews: 404,
        saves: 17,
        inquiries: 3,
        showingRequests: 1,
        openHouseAttendees: 4,
        brokerInquiries: 0,
        buyerLeads: 4,
        socialReach: 555,
        videoViews: 555,
      },
    },
    {
      weekLabel: 'Week 3',
      weekNumber: 3,
      metrics: {
        totalViews: 293,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 117,
        compassViews: 176,
        saves: 0,
        inquiries: 0,
        showingRequests: 0,
        openHouseAttendees: 0,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 4',
      weekNumber: 4,
      metrics: {
        totalViews: 285,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 134,
        compassViews: 151,
        saves: 0,
        inquiries: 0,
        showingRequests: 1,
        openHouseAttendees: 11,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 5',
      weekNumber: 5,
      metrics: {
        totalViews: 380,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 79,
        compassViews: 301,
        saves: 0,
        inquiries: 0,
        showingRequests: 0,
        openHouseAttendees: 0,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
  ],

  includedSections: {
    propertyOverview: false,
    weeklySnapshot:   true,
    openHouses:       true,
    marketing:        true,
    socialMedia:      true,
    feedback:         false,
    marketActivity:   false,
    strategy:         true,
  },

  openHouses: [
    {
      id: 'oh-baltic-000',
      date: '2026-05-10',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 2,
      brokers: 0,
      buyers: 2,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: '',
    },
    {
      id: 'oh-baltic-001',
      date: '2026-05-17',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 4,
      brokers: 3,
      buyers: 1,
      seriousInterestLevel: 4,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'One buyer requesting a second private showing — scheduled for Friday May 22.',
    },
    {
      id: 'oh-baltic-002',
      date: '2026-05-24',
      startTime: '12:00',
      endTime: '13:30',
      totalAttendees: 0,
      brokers: 0,
      buyers: 0,
      seriousInterestLevel: 1,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'Memorial Day weekend — no attendees.',
    },
    {
      id: 'oh-baltic-003',
      date: '2026-05-28',
      startTime: '18:30',
      endTime: '20:30',
      totalAttendees: 11,
      brokers: 11,
      buyers: 0,
      seriousInterestLevel: 4,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'Broker Open House — 11 NYC brokers attended. Strong showing from the broker network.',
    },
  ],

  marketing: [
    {
      id: 'mkt-baltic-001',
      type: 'instagram_reel',
      name: '@maggie_leigh_marshall — Open House Reel',
      date: '2026-05-16',
      impressions: 555,
      engagement: 36,
      clicks: 0,
      reach: 555,
      link: 'https://www.instagram.com/reel/DYYJSRdsVFO/',
      notes:
        'Reel on @maggie_leigh_marshall (Verified) announcing Sunday May 17 open house. Highlights 1,800 SF, two private terraces, floor-to-ceiling windows, panoramic skyline views. Collaboration with @soldbycy. Hashtags: #parkslope #balticparkslope #MM&Co.',
    },
    {
      id: 'mkt-baltic-stories',
      type: 'instagram_post',
      name: '@soldbycy — Instagram Story Series',
      date: '2026-05-14',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: '4-part Instagram story series posted by @soldbycy highlighting 613 Baltic Street Unit 9C. Property walkthrough and lifestyle content.',
    },
    {
      id: 'mkt-baltic-broker-blast',
      type: 'broker_outreach',
      name: 'Broker Blast — NYC Network',
      date: '2026-05-15',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes: 'Targeted email blast sent to 8,000+ NYC brokers announcing 613 Baltic Street, Unit 9C.',
    },
    {
      id: 'mkt-baltic-broker-blast-w3',
      type: 'broker_outreach',
      name: 'Broker Blast — NYC Network (weekly)',
      date: '2026-05-23',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes: 'Weekly broker blast — 8,000+ NYC brokers reminded of the listing and upcoming open houses.',
    },
    {
      id: 'mkt-baltic-w3-mm-post',
      type: 'instagram_post',
      name: '@maggie_leigh_marshall — Open House Post',
      date: '2026-05-23',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: 'Open house announcement post on @maggie_leigh_marshall (Verified) promoting the Sunday May 24 and Thursday May 28 open houses.',
    },
    {
      id: 'mkt-baltic-w3-soldbycy-post',
      type: 'instagram_post',
      name: '@soldbycy — Open House Post',
      date: '2026-05-27',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: 'Open house announcement post on @soldbycy promoting the May 28 Wine & Cheese Sunset Open House.',
    },
    {
      id: 'mkt-baltic-w3-stories',
      type: 'instagram_post',
      name: '@soldbycy + @maggie_leigh_marshall — Instagram Stories',
      date: '2026-05-26',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes: '3 Instagram stories across @soldbycy and @maggie_leigh_marshall featuring 613 Baltic Street, Unit 9C.',
    },
    {
      id: 'mkt-baltic-002',
      type: 'instagram_post',
      name: '@compassny — 613 Baltic Street Launch Post',
      date: '2026-05-20',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      link: 'https://www.instagram.com/p/DYm-xYpkUN_/',
      notes:
        'Posted on @compassny (Verified) and reshared across team accounts. Caption highlights corner 3BR/3.5BA, southwest exposures, outdoor space, parking + storage. Tagged @maggie_leigh_marshall.',
    },
    {
      id: 'mkt-baltic-w5-price-drop',
      type: 'instagram_post',
      name: '@maggie_leigh_marshall — Price Drop Announcement',
      date: '2026-06-09',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 0,
      notes:
        'Instagram post highlighting the recent price adjustment to $3,249,000 (down from $3,500,000). Drives new buyer attention and re-engages prior viewers.',
    },
    {
      id: 'mkt-baltic-w5-broker-blast',
      type: 'broker_outreach',
      name: 'Price Drop Broker Blast — NYC Network',
      date: '2026-06-09',
      impressions: 0,
      engagement: 0,
      clicks: 0,
      reach: 8000,
      notes:
        'Targeted email blast to the full NYC broker community announcing the price adjustment to $3,249,000. Reactivates brokers with $3M–$3.5M buyers who may not have looked at the higher price.',
    },
  ],

  socialMedia: [
    {
      platform: 'instagram',
      reelViews: 555,
      likes: 23,
      comments: 0,
      shares: 13,
      saves: 0,
      engagementRate: 0,
      followerGrowth: 0,
      bestContentDescription: '@maggie_leigh_marshall open house reel — 613 Baltic St, Unit 9C. 555 views.',
      bestContentViews: 555,
    },
  ],

  feedback: {
    items: [],
    commonObjections: '',
    pricingFeedback: '',
    layoutFeedback: '',
    competingProperties: '',
    brokerSentiment: '',
    recommendedAdjustments: '',
  },

  digitalAds: {
    campaignName: 'Location-Based Targeting',
    targetingFocus: 'Boerum Hill · Park Slope · Cobble Hill · Carroll Gardens · Brooklyn Heights · Fort Greene',
    reportingPeriod: 'May 29 – June 28, 2026',
    totalImpressions: 50126,
    totalClicks: 313,
    topChannel: { name: 'Instagram', ctr: 2.4 },
    // This week's social ad clicks-by-channel breakdown (Compass Digital Ads, Jun 9)
    byChannel: [
      { channel: 'Google',    clicks: 88, ctr: 1.82 },
      { channel: 'Facebook',  clicks: 19, ctr: 1.73 },
      { channel: 'Instagram', clicks: 14, ctr: 2.48 },
    ],
    // Where the location-based display ads showed up (May 29 – Jun 28 running totals)
    topPublishers: [
      { publisher: 'nytimes.com',     views: 13965 },
      { publisher: 'theatlantic.com', views: 4869  },
      { publisher: 'mlb.com',         views: 3795  },
      { publisher: 'nypost.com',      views: 3058  },
      { publisher: 'gothamist.com',   views: 2807  },
      { publisher: 'huffpost.com',    views: 1914  },
    ],
    audienceHouseholdIncome: [
      { bracket: 'Top 10%', share: 94.4 },
      { bracket: '41–50%',  share: 2.9  },
      { bracket: '21–30%',  share: 1.3  },
    ],
    socialTrafficPeriod: 'June 4 – June 10, 2026',
    socialTrafficShare: [
      { channel: 'Facebook',  share: 77.1 },
      { channel: 'Instagram', share: 22.9 },
    ],
  },

  marketActivity: {
    newListings: [],
    priceReductions: [],
    underContract: [],
    recentSales: [],
    neighborhoodTrends:
      'StreetEasy data: 613 Baltic is significantly outperforming comparable Park Slope listings on views — 463 total views in just 14 days against a median of 36.5 for similar homes. Median days to contract for comparable homes is 132 days. Strong early momentum positions the listing well.',
  },

  strategy: {
    keyRecommendations: '',
    marketingPlanNextWeek: '— Price-adjustment announcement push: new "$3.25M" creative across all social and display ads\n— Re-engage all prior open-house attendees and broker contacts with the new price\n— Refreshed Instagram reel on @maggie_leigh_marshall and @soldbycy highlighting the new price\n— Weekly broker blast to NYC network with price adjustment\n— Location-based display campaign continues through June 28 (NYT, Atlantic, NY Post, Gothamist, etc.)',
    pricingStrategy: '',
    upcomingCampaigns: '',
    brokerEvents: '',
    openHousesPlanned: '— Public open house: Sunday June 14, 1:00–2:30 PM (first showing at new $3.25M price)',
  },
}
