import { WeeklyReport } from './types'

/**
 * 266 West 71st Street — second active MM&Co listing.
 * Fill in the property fields (price, beds, baths, sqft, listing date,
 * photo URL, description) in the editor or update this file directly.
 */
export const WEST71_REPORT: WeeklyReport = {
  id: 'west71-266-w1',
  // Week number = weeks on market (listed May 27), not report count.
  weekNumber: 12,
  reportDate: '2026-08-24',
  // Traffic metrics are the Compass Insights pull covering Aug 13 – 19;
  // the window extends through Mon Aug 24 to capture Sunday's open house
  // (Aug 23) and Monday's private showing.
  weekStartDate: '2026-08-13',
  weekEndDate: '2026-08-24',

  property: {
    address: '266 West 71st Street',
    unit: '',
    neighborhood: 'Upper West Side',
    city: 'New York',
    state: 'NY',
    zip: '10023',
    price: 4_995_000,
    beds: 4,
    baths: 5,
    sqft: 3520,
    listingDate: '2026-05-27', // 71 days on market as of the Aug 6 report
    mainImageUrl: '/west71-hero.jpg',
    galleryImages: [],
    description:
      'A rare opportunity to restore and reimagine a historic Upper West Side townhouse on one of the neighborhood\u2019s most beautiful tree-lined blocks. Built in 1899 and rich with original architectural details — six fireplaces, intricate moldings, decorative paneling, and an elegant stoop entry. 3,520 square feet of light-filled space across four bedrooms and five bathrooms, offering extraordinary potential.',
    agent: {
      name: 'Maggie L. Marshall',
      title: 'Licensed Associate Real Estate Broker',
      team: 'MM&Co.',
      brokerage: 'Compass',
      phone: '917-838-4774',
      email: 'mlm@compass.com',
      photoUrl: '/613-baltic-agent.jpg',
      logoUrl: '/mmco-logo.png',
    },
    coAgents: [
      {
        name: 'Jonathan Banks',
        title: 'Licensed Associate Real Estate Broker',
        team: '',                       // Not on MM&Co. — just Compass
        brokerage: 'Compass',
        phone: '917-657-2252',
        email: '',
        photoUrl: '/jonathan-banks.jpg',
        logoUrl: '',
      },
    ],
  },

  // Week 12 (Aug 13 – 19) — Compass Insights:
  // 1,045 total views (down 34.2% over 7 days), 38 unique visitors (up 15.2%),
  // 42s avg time spent (up 40.1%), Compass top traffic source (94% of visitors),
  // 87% of Compass views from public.
  // Views by publisher: Realtor 734 / StreetEasy 257 / Compass 52 / Others 2.
  // Sunday Aug 23 public open house — 4 buyer groups. Private showing Mon
  // Aug 24 — 1 group. 5 groups through the home this week.
  currentMetrics: {
    totalViews: 1045,
    websiteTraffic: 0,
    zillowViews: 0,
    streetEasyViews: 257,
    compassViews: 52,
    saves: 0,
    inquiries: 0,
    showingRequests: 1,
    openHouseAttendees: 4,
    brokerInquiries: 0,
    buyerLeads: 0,
    socialReach: 0,
    videoViews: 0,
  },

  // Previous = Week 11 (Aug 6 – 16).
  previousMetrics: {
    totalViews: 1002,
    websiteTraffic: 0,
    zillowViews: 0,
    streetEasyViews: 268,
    compassViews: 37,
    saves: 0,
    inquiries: 1,
    showingRequests: 0,
    openHouseAttendees: 1,
    brokerInquiries: 0,
    buyerLeads: 1,
    socialReach: 0,
    videoViews: 0,
  },

  metricsHistory: [
    {
      weekLabel: 'Week 1',
      weekNumber: 1,
      metrics: {
        totalViews: 831,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 453,
        compassViews: 96,
        saves: 0,
        inquiries: 0,
        showingRequests: 5,
        openHouseAttendees: 0,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 2',
      weekNumber: 2,
      metrics: {
        totalViews: 770,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 264,
        compassViews: 89,
        saves: 0,
        inquiries: 0,
        showingRequests: 3,
        openHouseAttendees: 4,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 3',
      weekNumber: 3,
      metrics: {
        totalViews: 729,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 195,
        compassViews: 199,
        saves: 0,
        inquiries: 0,
        showingRequests: 0,
        openHouseAttendees: 0,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 10',
      weekNumber: 10,
      metrics: {
        totalViews: 0,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 0,
        compassViews: 0,
        saves: 0,
        inquiries: 0,
        showingRequests: 1,
        openHouseAttendees: 3,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 11',
      weekNumber: 11,
      metrics: {
        totalViews: 1002,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 268,
        compassViews: 37,
        saves: 0,
        inquiries: 1,
        showingRequests: 0,
        openHouseAttendees: 1,
        brokerInquiries: 0,
        buyerLeads: 1,
        socialReach: 0,
        videoViews: 0,
      },
    },
    {
      weekLabel: 'Week 12',
      weekNumber: 12,
      metrics: {
        totalViews: 1045,
        websiteTraffic: 0,
        zillowViews: 0,
        streetEasyViews: 257,
        compassViews: 52,
        saves: 0,
        inquiries: 0,
        showingRequests: 1,
        openHouseAttendees: 4,
        brokerInquiries: 0,
        buyerLeads: 0,
        socialReach: 0,
        videoViews: 0,
      },
    },
  ],

  includedSections: {
    propertyOverview: false,
    weeklySnapshot:   true,
    openHouses:       true,
    marketing:        false,
    socialMedia:      false,
    // Digital ads data on file is the Jun 28 – Jul 4 pull — re-enable once the
    // fresh Databox snapshot lands.
    digitalAds:       false,
    feedback:         false,
    marketActivity:   false,
    strategy:         true,
  },

  openHouses: [
    {
      id: 'oh-west71-preview',
      date: '2026-06-03',
      startTime: '14:00',
      endTime: '14:45',
      totalAttendees: 1,
      brokers: 0,
      buyers: 1,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: 'Private preview — one prospective buyer previewed the home.',
    },
    {
      id: 'oh-west71-w2-sun',
      kind: 'public',
      date: '2026-06-21',
      startTime: '13:00',
      endTime: '14:30',
      totalAttendees: 4,
      brokers: 0,
      buyers: 4,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: '',
    },
    // Jul 26 + Aug 2: 3 buyer parties total across the two Sundays.
    // Split assumed 2/1 — adjust in the editor if it was the other way around.
    {
      id: 'oh-west71-w4-sun1',
      kind: 'public',
      date: '2026-07-26',
      startTime: '13:00',
      endTime: '14:30',
      totalAttendees: 2,
      brokers: 0,
      buyers: 2,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: '',
    },
    {
      id: 'oh-west71-w4-sun2',
      kind: 'public',
      date: '2026-08-02',
      startTime: '13:00',
      endTime: '14:30',
      totalAttendees: 1,
      brokers: 0,
      buyers: 1,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: '',
    },
    // Aug 16 OH (1 visitor) removed from the page for Week 12 — falls inside
    // the Aug 13–24 window but belongs to last week's report.
    {
      id: 'oh-west71-w12-sun',
      kind: 'public',
      date: '2026-08-23',
      startTime: '13:00',
      endTime: '14:30',
      totalAttendees: 4,
      brokers: 0,
      buyers: 4,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: '',
    },
    {
      id: 'oh-west71-w12-private',
      kind: 'private_showing',
      date: '2026-08-24',
      startTime: '',
      endTime: '',
      totalAttendees: 1,
      brokers: 0,
      buyers: 1,
      seriousInterestLevel: 3,
      commonFeedback: '',
      questionsAsked: '',
      followUpActions: '',
    },
  ],

  marketing: [],

  socialMedia: [],

  feedback: {
    items: [],
    commonObjections: '',
    pricingFeedback: '',
    layoutFeedback: '',
    competingProperties: '',
    brokerSentiment: 'The strongest week of in-person activity this month: Sunday’s open house on August 23 brought four buyer groups through, and a private showing on Monday, August 24 made it five groups total for the week. Online, the listing drew 1,045 views led by Realtor.com (734) and StreetEasy (257), and while total views cooled with the late-summer market, engagement deepened — unique visitors rose 15.2% and average time on the listing jumped 40.1% to 42 seconds, a sign the buyers who are looking are looking closely.',
    recommendedAdjustments: '',
  },

  digitalAds: {
    campaignName: 'Location-Based Targeting',
    targetingFocus: 'Upper West Side · Lincoln Square · Central Park West · Riverside · Columbus Ave',
    // Latest Compass Digital Ads pull — Jun 28 – Jul 4, 2026 (Databox).
    reportingPeriod: 'Jun 28 – Jul 4, 2026',
    totalImpressions: 10054,
    totalClicks: 183,
    topChannel: { name: 'nytimes.com', ctr: 1.82 },
    byChannel: [],
    // Top 12 publishers from the Jun 28 – Jul 4 Databox snapshot.
    topPublishers: [
      { publisher: 'nytimes.com',       views: 3758 },
      { publisher: 'nypost.com',        views: 952  },
      { publisher: 'foxnews.com',       views: 751  },
      { publisher: 'cnn.com',           views: 364  },
      { publisher: 'yahoo.com',         views: 314  },
      { publisher: 'theguardian.com',   views: 299  },
      { publisher: 'huffpost.com',      views: 273  },
      { publisher: 'thedailybeast.com', views: 259  },
      { publisher: 'cbssports.com',     views: 162  },
      { publisher: 'triblive.com',      views: 160  },
      { publisher: 'cnbc.com',          views: 144  },
      { publisher: 'pagesix.com',       views: 107  },
    ],
    audienceHouseholdIncome: [
      { bracket: 'Top 10%', share: 90.1 },
      { bracket: '11–20%',  share: 5.2  },
      { bracket: '21–30%',  share: 3.1  },
    ],
    socialTrafficPeriod: 'Jun 29 – Jul 5, 2026',
    socialTrafficShare: [],
  },

  marketActivity: {
    newListings: [],
    priceReductions: [],
    underContract: [],
    recentSales: [],
    neighborhoodTrends: '',
  },

  strategy: {
    keyRecommendations: 'Momentum is building heading into the fall market: five buyer groups saw the home this week — the most in-person activity since launch — and engagement metrics online moved the right way, with unique visitors up 15.2% and time on the listing up 40.1%. The focus now is converting that foot traffic: prompt follow-up with all five groups while interest is fresh, and keeping the Sunday open-house cadence going as buyers return from summer.',
    marketingPlanNextWeek: '— Follow up with all four buyer groups from the August 23 open house\n— Follow up with the August 24 private showing\n— Continue the Sunday open-house cadence into the fall market\n— Renewed broker outreach to Upper West Side buyer agents',
    pricingStrategy: '',
    upcomingCampaigns: '',
    brokerEvents: '',
    openHousesPlanned: '',
  },
}
